# Generated by Django 4.2.4 on 2023-08-21 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Titulo')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('locacion', models.CharField(max_length=100, verbose_name='Locacion')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('metros_cuadrados', models.PositiveIntegerField(verbose_name='Metros Cuadrados')),
                ('habitaciones', models.PositiveSmallIntegerField(verbose_name='Habitaciones')),
                ('baños', models.PositiveSmallIntegerField(verbose_name='Baños')),
                ('piscina', models.BooleanField(verbose_name='Piscina')),
                ('garage', models.BooleanField(verbose_name='Garage')),
                ('contrato', models.CharField(max_length=10, verbose_name='Contrato')),
                ('año_construccion', models.CharField(max_length=5, verbose_name='Año Construccion')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, upload_to=None, verbose_name='Imagen')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.vendedor')),
            ],
        ),
    ]
